name: Force Deploy to Cloudflare Pages

on:
  workflow_dispatch:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.147.9'
          extended: true
          
      - name: Build Hugo site
        run: |
          hugo --minify --gc --cleanDestinationDir --forceSyncStatic
        env:
          HUGO_ENV: production
          
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name=netfilesnext --compatibility-date=2024-01-01 --force